/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:9627dc6f-2619-44ef-9ecb-d2e2b6b5abb7",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_bvcx4xU4T",
    "aws_user_pools_web_client_id": "40eorp492dqf3ghp7qijoobn2f",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://7sgd6izkuzbbdc37nrqoido73u.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-z4lrwn6wcvfhhop35bvfjmyjfy",
    "aws_user_files_s3_bucket": "amplifyapp74fa86569ff643de88eff938497b4c0f230047-dev",
    "aws_user_files_s3_bucket_region": "us-west-2"
};


export default awsmobile;
